DELETE http://localhost:8080/api/guests

###

DELETE http://localhost:8080/api/guests/12

###

PUT http://localhost:8080/api/guests/12
Content-Type: application/json

{
"name": "Kapás Boglárka"
}

###

POST http://localhost:8080/api/guests/12/room
Content-Type: application/json

{
"roomNumber": "H2"
}

###

POST http://localhost:8080/api/guests
Content-Type: application/json

{
"name": "Margot Robbie"
}

###

POST http://localhost:8080/api/guests
Content-Type: application/json

{
"name": "Jennifer Aniston"
}

###

GET http://localhost:8080/api/guests/8
Accept: application/json

###

GET http://localhost:8080/api/guests
Accept: application/json
