DELETE http://localhost:8080/api/rooms

###

DELETE http://localhost:8080/api/rooms/31

###

PUT http://localhost:8080/api/rooms/33/guest
Content-Type: application/json

{
"id": 14
}

###

POST http://localhost:8080/api/rooms/32/guest
Content-Type: application/json

{
"name": "Mila Kunis"
}

###

POST http://localhost:8080/api/rooms
Content-Type: application/json

{
"roomNumber": "H4"
}

###

POST http://localhost:8080/api/rooms
Content-Type: application/json

{
"roomNumber": "H3"
}

###

GET http://localhost:8080/api/rooms/33
Accept: application/json

###

GET http://localhost:8080/api/rooms
Accept: application/json
